package cn.ntboy.model;

import lombok.ToString;

@ToString
public class Menus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.id
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.name
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.typeid
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    private String typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.burden
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    private String burden;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.brief
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    private String brief;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.price
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.sums
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    private String sums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.price1
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    private String price1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.sums1
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    private String sums1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.imgpath
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    private String imgpath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.id
     *
     * @return the value of menus.id
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.id
     *
     * @param id the value for menus.id
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.name
     *
     * @return the value of menus.name
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.name
     *
     * @param name the value for menus.name
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.typeid
     *
     * @return the value of menus.typeid
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    public String getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.typeid
     *
     * @param typeid the value for menus.typeid
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    public void setTypeid(String typeid) {
        this.typeid = typeid == null ? null : typeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.burden
     *
     * @return the value of menus.burden
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    public String getBurden() {
        return burden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.burden
     *
     * @param burden the value for menus.burden
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    public void setBurden(String burden) {
        this.burden = burden == null ? null : burden.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.brief
     *
     * @return the value of menus.brief
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.brief
     *
     * @param brief the value for menus.brief
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    public void setBrief(String brief) {
        this.brief = brief == null ? null : brief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.price
     *
     * @return the value of menus.price
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.price
     *
     * @param price the value for menus.price
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.sums
     *
     * @return the value of menus.sums
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    public String getSums() {
        return sums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.sums
     *
     * @param sums the value for menus.sums
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    public void setSums(String sums) {
        this.sums = sums == null ? null : sums.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.price1
     *
     * @return the value of menus.price1
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    public String getPrice1() {
        return price1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.price1
     *
     * @param price1 the value for menus.price1
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    public void setPrice1(String price1) {
        this.price1 = price1 == null ? null : price1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.sums1
     *
     * @return the value of menus.sums1
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    public String getSums1() {
        return sums1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.sums1
     *
     * @param sums1 the value for menus.sums1
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    public void setSums1(String sums1) {
        this.sums1 = sums1 == null ? null : sums1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.imgpath
     *
     * @return the value of menus.imgpath
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    public String getImgpath() {
        return imgpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.imgpath
     *
     * @param imgpath the value for menus.imgpath
     *
     * @mbg.generated Thu Oct 24 11:24:48 CST 2019
     */
    public void setImgpath(String imgpath) {
        this.imgpath = imgpath == null ? null : imgpath.trim();
    }
}